from src.stix_parser import StixParser
from src.markdown_generator import MarkdownGenerator
import argparse
import datetime
import os
import yaml

if __name__ == '__main__':
    domains = ['enterprise-attack', 'mobile-attack', 'ics-attack']
    parser = argparse.ArgumentParser(description='Download MITRE ATT&CK STIX data and parse it to Obsidian markdown notes')

    parser.add_argument('--path', help="Filepath to the markdown note file")
    parser.add_argument('-o', '--output', help="Output directory in which the notes will be saved. It should be placed inside a Obsidian vault.")

    args = parser.parse_args()

    with open('config.yml', 'r') as fd:
        config = yaml.safe_load(fd)

    if not args.output:
        raise ValueError("You need to provide an output directory")
    
    # Main functionality
    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    for domain in domains:
        stix_data = StixParser(config['repository_url'], domain, version=config['version'])
        stix_data.get_data()

        output_dir = args.output + '/' + domain.replace('-', ' ').capitalize().replace('Ics ', 'ICS ')
        if not os.path.exists(output_dir):
            os.mkdir(output_dir)
        markdown_generator = MarkdownGenerator(output_dir, stix_data.techniques, stix_data.groups, stix_data.tactics, stix_data.mitigations, stix_data.software, stix_data.campaigns)
        markdown_generator.create_tactic_notes()
        markdown_generator.create_technique_notes()
        markdown_generator.create_mitigation_notes()

        if domain == 'enterprise-attack':
            markdown_generator.create_software_notes()
            markdown_generator.create_group_notes()
            markdown_generator.create_campaign_notes()

    # Generate Main README file
    attack_file = os.path.join(args.output, "MITRE ATT&CK.md")
    if not os.path.exists(attack_file):
        with open(attack_file, 'w') as fd:
            content = "---\nalias: MITRE ATT&CK®\n---\n\n"

            content += "# MITRE ATT&CK®\n\n"
            content += "This is a collection pf pages for Obsidian of the MITRE ATT&CK® framework.\n\n"
            content += "Generated by [obsidian-mitre-attack](https://github.com/reuteras/obsidian-mitre-attack) on " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ".\n\n"
            content += "This collection is based on the following MITRE ATT&CK® domains:\n\n" 
            for domain in domains:
                content += "- " + domain + " version " + str(config['version']) + ".\n"  
            content += "\n"
            fd.write(content) 
